version: "3.9"
name: ark

services:
  prometheus:
    image: prom/prometheus:v2.47.0
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus_data:/prometheus
    ports:
      - "9090:9090"

  redis:
    image: redis:7.2.1
    volumes:
      - redis_data:/data
    entrypoint:
      - redis-server
      - --save 30 1
    ports:
      - "6379:6379"

  server:
    image: ghcr.io/fedragon/ark:v1.0.0-rc1
    ports:
      - "9999:9999"
    volumes:
      - ark_data:/ark
    environment:
      ARK_SERVER_ADDRESS: "0.0.0.0:9999"
      ARK_SERVER_ARCHIVE_PATH: /ark
      ARK_SERVER_REDIS_ADDRESS: "redis:6379"
      ARK_SERVER_REDIS_DATABASE: 0
    secrets:
      - server
    entrypoint:
      - bin/sh
      - -c
      - 'source /run/secrets/server && /bin/server'
    depends_on:
      - prometheus
      - redis

secrets:
  server:
    file: ./secrets/server

volumes:
  ark_data:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: './data/archive'
  prometheus_data:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: './data/prometheus'
  redis_data:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: './data/redis'
