name: Go

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: '1.20.x'
        
    - name: Test
      run: go test -v ./...

    - name: Build Server
      run: |
        mkdir -p bin
        go build -v -o bin/server cmd/server/main.go
      
    - name: Build Client
      run: |
        mkdir -p bin
        go build -v -o bin/client cmd/client/main.go
